### ISSUE TITLE
Fails to read MagicaVoxel file

### ISSUE THREAD

**Issue by inxomnyaa** [Kristopher38/vox2schematic#1]
```log
python.exe .\vox2schematic.py ..\model\shrunk\wf_sky_ps_meshsampler.vox
Traceback (most recent call last):
  File ".\vox2schematic.py", line 102, in <module>
    main()
  File ".\vox2schematic.py", line 98, in main
    w, l, h, blocks, data = handlers[args.format](args)
  File ".\vox2schematic.py", line 67, in vox_handler
    model = VoxParser(args.filename).parse()
  File "C:\Users\XenialDan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyvox\parser.py", line 93, in parse
    main = self._parseChunk()
  File "C:\Users\XenialDan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyvox\parser.py", line 81, in _parseChunk
    chunks.append(self._parseChunk())
  File "C:\Users\XenialDan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyvox\parser.py", line 83, in _parseChunk
    return Chunk(_id, content, chunks)
  File "C:\Users\XenialDan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyvox\parser.py", line 55, in __init__
    raise ParsingException('Unknown chunk type: %s'%self.id)
pyvox.parser.ParsingException: Unknown chunk type: b'MATL'
```
or
```log
python.exe .\vox2schematic.py ..\model\shrunk\wf_sky_ps_meshsampler_to_magica.vox
Traceback (most recent call last):
  File ".\vox2schematic.py", line 102, in <module>
    main()
  File ".\vox2schematic.py", line 98, in main
    w, l, h, blocks, data = handlers[args.format](args)
  File ".\vox2schematic.py", line 67, in vox_handler
    model = VoxParser(args.filename).parse()
  File "C:\Users\XenialDan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyvox\parser.py", line 93, in parse
    main = self._parseChunk()
  File "C:\Users\XenialDan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyvox\parser.py", line 81, in _parseChunk
    chunks.append(self._parseChunk())
  File "C:\Users\XenialDan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyvox\parser.py", line 83, in _parseChunk
    return Chunk(_id, content, chunks)
  File "C:\Users\XenialDan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyvox\parser.py", line 55, in __init__
    raise ParsingException('Unknown chunk type: %s'%self.id)
pyvox.parser.ParsingException: Unknown chunk type: b'nTRN'
```

**Comment by inxomnyaa** [comment]
Hmmm nervermind, seems like the lib used has issues. https://github.com/alexhunsley/numpy-vox-io/issues/4
